### ISSUE TITLE
Datasets deletion issue

### ISSUE THREAD

**Issue by Daniellappv** [nhsbsa-data-analytics/open-data-roadmap#176]
## Overview

Hi Datopian,

This issue was noted on 2025-07-18 during UAT testing and documented on my side but I fear it may have been either lost in the google chat or never raised by me – apologies:

(In both staging and prod) Selecting and deleting one dataset deletes more than one dataset if another dataset of the same status (e.g. draft) exists:

<img width="809" height="607" alt="Image" src="https://github.com/user-attachments/assets/d20f9fc9-9170-4093-9802-2dfa11b48ac9" />

<img width="1334" height="924" alt="Image" src="https://github.com/user-attachments/assets/14a91cf1-7823-44f9-87ee-cb46a5e7eef8" />

Thank you,
Kate

**Comment by amautadev** [comment]
@NHSBSA-Open-Data, I ve taken the task and now reviewing the causes of issue. Will keep you posted.


CC: @Daniellappv

**Comment by amautadev** [comment]
I have tested locally on my side draft dataset is not included in deletion list. But on staging and prod I see they exist and more than one draft datasets are deleted when delete process is done only for one. This is primarily core ckan action, but I believe one of extensions of portal has some overrides over this deletion action. Will keep you posted

CC: @NHSBSA-Open-Data

**Comment by amautadev** [comment]
@NHSBSA-Open-Data, I have tested deleting via API calls draft datasets with different statuses (public/private, draft/notdraft). Deletion goes for single chosen dataset with no additional removals. So I see that this issue is on UI part.

I have deleted via UI one draft dataset and it deletes all drafts. However, if you go to dataset page of this theme again or reload, you will see that draft dataset has not been deleted.

Next steps of mine will be to check the logs whether the request is sent correctly for draft datasets

**Comment by amautadev** [comment]
@NHSBSA-Open-Data the I have reproduced locally the bug and identified the issue. Draft deletion went directly via script which deleted only on UI, but not entirely. That's why I wrote the new patch to delete via ckan core actions. Now the draft datasets are deleted safely locally. I will need today to put new patches into deployment to staging.

CC: @Daniellappv

**Comment by amautadev** [comment]
@NHSBSA-Open-Data patches are applied, however as we moved /organization to /theme and we stick to /theme, I will fix redirect to go to /theme. 

Curretnly after deletion it goes to /organization thus you might still see issue

**Comment by amautadev** [comment]
@NHSBSA-Open-Data the issue has been resolved, could you please test it on your side, thanks

**Comment by NHSBSA-Open-Data** [comment]
@AlmubdyMutaikhan I think there is still an issue, please:

Looks to be deleted, and can delete one draft at a time, for example:

<img width="1363" height="871" alt="Image" src="https://github.com/user-attachments/assets/5cabb23f-d829-4a39-a298-7915ccf1b161" />

But the datasets are not deleted:

<img width="1347" height="978" alt="Image" src="https://github.com/user-attachments/assets/7a8fa96e-592a-414b-88fa-e4d725e7fd86" />

Thank you,
Kate

**Comment by amautadev** [comment]
@NHSBSA-Open-Data I believe there is a new issue, if you reload the page multiple times, then you will see that dataset has been deleted. Curretnly I have deleted that Uplaoder Testing final draft and created one more draft hello_world.
Thus when I reloaded several times, I see it shows different number of datasets.

If you look on left sidebar, then metadata says that there left Datasets: 1
Will investigate why it so happens

**Comment by amautadev** [comment]
@NHSBSA-Open-Data could you please test it now? We have reindexed solr as we had earlier broken dataset deletion method which deleted on DB, but not on solr

I have created several drafts and datasets and reloaded the page, from my end the no issue has been detected.

Thanks

**Comment by NHSBSA-Open-Data** [comment]
@AlmubdyMutaikhan As per your google-chat comment, I have checked the dataset deletion in staging and can confirm that this now appears to be working as expect. So is only deleting the chosen datasets and is actually deleting them - when navigating away and coming back to the datasets list these datasets do not re-appear.

Please could you add this to the prod deployment queue if not already there.

Thank you,
Kate

**Comment by amautadev** [comment]
> [@AlmubdyMutaikhan](https://github.com/AlmubdyMutaikhan) As per your google-chat comment, I have checked the dataset deletion in staging and can confirm that this now appears to be working as expect. So is only deleting the chosen datasets and is actually deleting them - when navigating away and coming back to the datasets list these datasets do not re-appear.
> 
> Please could you add this to the prod deployment queue if not already there.
> 
> Thank you, Kate

@NHSBSA-Open-Data sure, thanks.
