### ISSUE TITLE
Feedback log table

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [nhsbsa-data-analytics/open-data-roadmap#182]
Hello Datopian,

I’m struggling with the following table:

https://opendata.nhsbsa.net/pages/feedback-log

This was working how I wanted it to as of 30/07/2025 – i.e. the ‘show more’ was hiding large pieces of text and when clicked it was dropping vertically to display the full text under the cut.

Now, as you can see, for some reason Feedback Content and Notes are stretching horizontally across the page resulting in an awful looking Feedback log and users having to scroll to view the full text – which is not acceptable.

Are you able to please assist if possible.

Thank you so much,
Kate

**Comment by Uchechukwu-Onye-Igbo** [comment]
hello @AlmubdyMutaikhan when do you think you can get to this issue?

**Comment by sneha-sharma12** [comment]
Hi Kate

We are looking into this. Will keep you posted.

Thanks

**Comment by sneha-sharma12** [comment]
Hi @NHSBSA-Open-Data 

The fix is deployed on dev. Can you please validate?
https://ckan.nhs.dev.datopian.com/pages/feedback-log

Thanks

**Comment by NHSBSA-Open-Data** [comment]
@sneha-sharma12 Apologies but this is not resolved.

The code live on ODP now for the feedback log produces the following on HTML preview sites:

<img width="1891" height="457" alt="Image" src="https://github.com/user-attachments/assets/fc78b42a-2c1b-4516-a8ec-70908ee2451c" />

Something in ODP is preventing the code from showing how it should do (and previously was on ODP), please.

Thank you,
Kate

**Comment by sneha-sharma12** [comment]
Hi @NHSBSA-Open-Data 

Could you please elaborate more on what exactly the issue is? 

As per my understanding, the issue is the UI of the table, which is fixed in the Dev, not in production 



**Prod**

<img width="1438" height="648" alt="Image" src="https://github.com/user-attachments/assets/77413068-d2dc-426f-8308-a9dd2c929e0b" />


**Dev**

<img width="1440" height="861" alt="Image" src="https://github.com/user-attachments/assets/239dff8c-01d7-4440-a666-e0aef78944fe" />

Thanks

**Comment by NHSBSA-Open-Data** [comment]
@sneha-sharma12 Apologies, I will see if I can explain.

So the fix in Dev should look like this:

<img width="1891" height="457" alt="Image" src="https://github.com/user-attachments/assets/5bd077a6-18af-42f3-bda8-90927f11c15a" />

But it does not. 

The feedback log you have provided in Dev currently for me to test is not reflective of the code which is currently saved against the feedback log in the prod system. When viewing the feedback log in the prod system, as per the screenshot you have provided above, this is not reflective of the code saved against the feedback log in prod currently. 

What I am saving is not what is being shown on screen - but it was showing previously and Michael Smith can attest to this. It should have 'Show More' buttons and associated hidden text - as per the code which is saved when you click on Source:

<p>At the NHSBSA, we are committed to ensuring transparency and making our data as accessible as possible for all users.</p>

<p>This Feedback Log records all feedback in relation to the Open Data Portal which is gathered through our <a href="https://online1.snapsurveys.com/Interview/e7672047-bda0-4934-94b7-c6625684665e">Customer Satisfaction Survey</a> or by contacting our support team directly via email at <a href="mailto:DataServicesSupport@NHSBSA.nhs.uk">DataServicesSupport@NHSBSA.nhs.uk</a>.</p>

<p><button class="nhsuk-button" type="button">Download CSV</button></p>

<div class="table-container">
<table class="nhsuk-table">
	<thead class="nhsuk-table__head" role="rowgroup">
		<tr role="row">
			<th scope="col">Date Received</th>
			<th scope="col">Feedback Summary</th>
			<th scope="col">Feedback Type</th>
			<th scope="col">CSAT Score</th>
			<th scope="col">Category</th>
			<th scope="col">Actions Taken</th>
			<th scope="col">Priority</th>
			<th scope="col">Status</th>
			<th scope="col">Feedback Content</th>
			<th scope="col">Notes</th>
		</tr>
	</thead>
	<tbody class="nhsuk-table__body">
		<tr>
			<td>2025-07-23</td>
			<td>English Prescribing Dataset (EPD) filters not working</td>
			<td>ODP &#39;Report an Issue&#39; button</td>
			<td>N/A</td>
			<td>Technical Issue</td>
			<td>Confirmed issue was not present during testing</td>
			<td>High</td>
			<td>Completed</td>
			<td>Unable to filter data to enable much reduced download</td>
			<td>
			<div class="truncated toggle-content">Two Data Services colleagues checked and confirmed filters were working correctly on 2025-07-24</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
		</tr>
		<tr class="nhsuk-table__row">
			<td>2025-05-30</td>
			<td>DATA ERROR: Prescriber Details: April 2025</td>
			<td>Email</td>
			<td>N/A</td>
			<td>Technical Issue</td>
			<td>Raised with data provider for correction</td>
			<td>High</td>
			<td>Completed</td>
			<td>
			<div class="truncated toggle-content">Hello, The latest &lsquo;Prescriber Details&rsquo; CSV file for April 2025 has erroneous values in the &lsquo;PROVIDER_SICBL_CODE&rsquo; column. Instead of a 5 character code, five Providers (given below) have codes that are in scientific/exponential notation, e.g. &#39;1.00E+00&#39; ICBs with erroneous PROVIDER_SICBL_CODE: 01E - LANCASHIRE AND SOUTH CUMBRIA ICB 15E - BIRMINGHAM AND SOLIHULL ICB 02E - CHESHIRE AND MERSEYSIDE ICB 71E - LINCOLNSHIRE ICB 99E - MID AND SOUTH ESSEX ICB</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
			<td>
			<div class="truncated toggle-content">Issue identified on 2025-05-30 and confirmed. Resolved 2025-06-03.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
		</tr>
		<tr class="nhsuk-table__row">
			<td>2025-05-01</td>
			<td>Data download problem or error</td>
			<td>ODP &#39;Report an Issue&#39; button</td>
			<td>N/A</td>
			<td>Technical Issue</td>
			<td>Checked all data and confirmed no subsequent action required</td>
			<td>High</td>
			<td>Completed</td>
			<td>
			<div class="truncated toggle-content">Hello Team, Please urgently assist. Cannot download all products for the following, has this changed from a few months ago please? Please can you fix to same format as a few months ago. Aflibercept, Dexamethasone, Faricimab, Fluocinolone acetonide, Ranibizumab, Sodium Chloride 5% eye drops, Fluocinolone acetonide</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
			<td>
			<div class="truncated toggle-content">2025-05-02 Checked against data which appears in ePACT2 and can confirm no prescribing appears for Aflibercept or Ranibizumab at all since Sept 2024 at least. Faricimab is a Hospital Only drug. The CHEMICAL_SUBSTANCE_BNF_DESCR in ODP for Dexamethasone, and Fluocinolone acetonide returns results. BNF_DESCRIPTION in ODP for Sodium Chloride 5% eye drops returns results. Therefore no action required to be taken as data appears correct when the above information is considered.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
		</tr>
		<tr class="nhsuk-table__row">
			<td>2025-02-28</td>
			<td>English Prescribing Dataset (EPD) - Downloaded file is empty</td>
			<td>ODP &#39;Report an Issue&#39; button</td>
			<td>N/A</td>
			<td>Technical Issue</td>
			<td>Raised with Datopian as an urgent issue</td>
			<td>High</td>
			<td>Resolved</td>
			<td>
			<div class="truncated toggle-content">When exporting the data for Dexcom One+ sensor, values are visible on screen but the downloaded Excel file is empty.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
			<td>
			<div class="truncated toggle-content">Fix live deployed 2025-03-28.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
		</tr>
		<tr class="nhsuk-table__row">
			<td>2025-01-28</td>
			<td>Overseas Healthcare Services - Cost Recovery: 503 error</td>
			<td>ODP &#39;Report an Issue&#39; button</td>
			<td>N/A</td>
			<td>Technical Issue</td>
			<td>Confirmed issue was not present during testing</td>
			<td>High</td>
			<td>Completed</td>
			<td>
			<div class="truncated toggle-content">503 error encountered when clicking data link; later, captcha error when trying to report.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
			<td>
			<div class="truncated toggle-content">Confirmed resolved on 28-01-2025; no further action taken.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
		</tr>
		<tr class="nhsuk-table__row">
			<td>2024-12-12</td>
			<td>Overall satisfaction: 8</td>
			<td>CSAT Survey</td>
			<td>8</td>
			<td>General Feedback</td>
			<td>Not required</td>
			<td>Low</td>
			<td>Completed</td>
			<td>
			<div class="truncated toggle-content">It wasn&#39;t easy to find GP (as in Prescriber) details.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
			<td>
			<div class="truncated toggle-content">No suggestions or technical issues provided.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
		</tr>
		<tr class="nhsuk-table__row">
			<td>2024-09-10</td>
			<td>Too much scrolling to access data files</td>
			<td>CSAT Survey</td>
			<td>1</td>
			<td>Improvement</td>
			<td>Exploring potential development</td>
			<td>Medium</td>
			<td>In Progress</td>
			<td>
			<div class="truncated toggle-content">The page layout makes it difficult to access data quickly.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
			<td>
			<div class="truncated toggle-content">Looking at adding a direct link to the data and resources at the top.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
		</tr>
		<tr class="nhsuk-table__row">
			<td>2024-09-09</td>
			<td>*Rows are not ordered in the data correctly</td>
			<td>CSAT Survey</td>
			<td>8</td>
			<td>Improvement</td>
			<td>Added to development</td>
			<td>High</td>
			<td>In Progress</td>
			<td>
			<div class="truncated toggle-content">This relates to the new IHS dataset. The data appears unordered. It should be arranged by month with the most recent at the top.</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
			<td>
			<div class="truncated toggle-content">Related to a current ticket</div>
			<span class="show-toggle" onclick="toggleExpand(this)">Show more</span></td>
		</tr>
	</tbody>
</table>
</div>
<style type="text/css">.table-container {
  width: 100%;
  max-width: 100%;
  margin: 0;
  padding: 0;
  background-color: white;
  box-sizing: content-box;
}

.nhsuk-table {
  width: 100%;
  table-layout: fixed;
  border-collapse: collapse;
  box-sizing: border-box;
  font-size: 1.3rem !important; /* force smaller font */
}

.nhsuk-table th,
.nhsuk-table td {
  padding: 0.25rem;
  border-bottom: 1px solid #ccc;
  vertical-align: top;
  text-align: left;
  white-space: normal;
  word-break: normal;
  min-width: 100px;
  font-size: 1.3rem !important; /* force smaller font */
}

.nhsuk-table th:nth-child(2),
.nhsuk-table td:nth-child(2),
.nhsuk-table th:nth-child(6),
.nhsuk-table td:nth-child(6) {
  min-width: 150px;
}

.nhsuk-table th:nth-child(9),
.nhsuk-table td:nth-child(9),
.nhsuk-table th:nth-child(10),
.nhsuk-table td:nth-child(10) {
  min-width: 200px;
}

.truncated {
  max-height: 12em;
  overflow: hidden;
  display: -webkit-box;
  -webkit-line-clamp: 8;
  -webkit-box-orient: vertical;
}

.expanded {
  max-height: none;
  -webkit-line-clamp: unset;
}

.show-toggle {
  color: #0065A4;
  cursor: pointer;
  font-size: 1rem;
  display: inline-block;
  margin-top: 5px;
}

.nhsuk-button {
  display: block;
  margin: 20px auto;
  padding: 12px 24px;
  background-color: #0065A4;
  color: white;
  text-align: center;
  border-radius: 4px;
  font-size: 1.25rem;
  cursor: pointer;
}

.nhsuk-button:hover {
  background-color: #004C73;
}
</style>
<script>
  // Download CSV functionality
  document.querySelector('.nhsuk-button').addEventListener('click', function () {
    const rows = document.querySelectorAll('.nhsuk-table tr');
    let csvContent = "";

    rows.forEach(row => {
      const cols = row.querySelectorAll('th, td');
      const rowData = Array.from(cols).map(col => {
        const temp = document.createElement("div");
        temp.innerHTML = col.innerHTML;
        let text = temp.textContent || temp.innerText || "";
        text = text.replace(/\n/g, ' ').replace(/"/g, '""');
        return `"${text.trim()}"`;
      }).join(",");
      csvContent += rowData + "\n";
    });

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", "feedback_log.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  });

  // Expand/collapse content
  function toggleExpand(toggle) {
    const content = toggle.previousElementSibling;
    const isExpanded = content.classList.toggle("expanded");
    if (isExpanded) {
      content.classList.remove("truncated");
      toggle.textContent = "Show less";
    } else {
      content.classList.add("truncated");
      toggle.textContent = "Show more";
    }
  }

  // Hide "Show more" where content isn't truncated
  function hideUnusedShowToggles() {
    const toggles = document.querySelectorAll('.toggle-content');
    toggles.forEach(content => {
      const toggleLink = content.nextElementSibling;
      // Ensure it's in truncated mode to test overflow
      content.classList.add('truncated');
      const isOverflowing = content.scrollHeight > content.offsetHeight;

      if (!isOverflowing && toggleLink && toggleLink.classList.contains('show-toggle')) {
        toggleLink.style.display = 'none';
      }
    });
  }

  // Run after content loads
  window.addEventListener('DOMContentLoaded', hideUnusedShowToggles);
</script>

Does this explain it better please?

Thank you,
Kate

**Comment by sneha-sharma12** [comment]
Hi @NHSBSA-Open-Data 

Appreciate your kind response, and thank you for explaining in detail. It is much clearer now. I have updated the source in the feedback log. Can you please validate again in dev?
https://ckan.nhs.dev.datopian.com/pages/feedback-log

<img width="1437" height="849" alt="Image" src="https://github.com/user-attachments/assets/5afb5b0c-4df6-4d81-9e7e-614937467f40" />

Thanks

**Comment by NHSBSA-Open-Data** [comment]
@sneha-sharma12 This was previously showing all within the centre column but without having the scroll-bar along the bottom - ideally, we'd want to avoid the addition of any further scroll-bars on a page. The font was a bit smaller but both myself and Michael were happy with it.

What was the reason as to why my original table has been changed, please? Just so I know if it is something I am doing or need to avoid in the future.

Thank you,
Kate

**Comment by sneha-sharma12** [comment]
Hi @NHSBSA-Open-Data 

Now it's correct? If yes, then this change came after the implementation of https://github.com/nhsbsa-data-analytics/Open-Data-Portal/issues/169#issuecomment-3137415365
The table in the edit and the table mentioned above share the same class, and a horizontal scroll was added for the table. We need to override the CSS for the table source of the page. Once you confirm if this is what you are expecting, I will share the changes with you. 

<img width="1440" height="780" alt="Image" src="https://github.com/user-attachments/assets/0a74c68f-2ba9-4674-b1d2-e7ab451f3e22" />


Thanks

**Comment by NHSBSA-Open-Data** [comment]
@sneha-sharma12 Yes, that looks perfect now - thank you.
 Kate

**Comment by sneha-sharma12** [comment]
Hi @NHSBSA-Open-Data 
Thanks for confirming. Do we need to move these changes to prod?
The solution was to add inline CSS to the table `<table class="nhsuk-table" style="width: 100%; display: table;">`

<img width="1186" height="491" alt="Image" src="https://github.com/user-attachments/assets/deda7b9b-4841-4946-a681-98e44e091251" />

**Comment by NHSBSA-Open-Data** [comment]
@sneha-sharma12 Thank you for providing the code - I have popped that into the prod feedback log and it is working as expected now.

Thank you again,
Kate
